### ISSUE TITLE
Error when running gulp right after the install

### ISSUE THREAD

**Issue by aurerua** [sondr3/generator-jekyllized#135]
Hi, and thanks a lot for this generator.

I get an error that I haven't managed to solve when running `gulp` right after installing the generator.

Any help appreciated. Thanks in advance!

```
$ gulp
/home/ubuntu/workspace/gulpfile.js:159
      imagemin.gifsicle({interlaced: true}),
              ^

SyntaxError: Unexpected token .
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at execute (/home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/gulp-cli/lib/versioned/^4.0.0-alpha.2/index.js:32:3)
    at Liftoff.handleArguments (/home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/gulp-cli/index.js:150:63)
    at Liftoff.<anonymous> (/home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/gulp-cli/node_modules/liftoff/index.js:193:16)
```

**Comment by sondr3** [comment]
Ah bollocks, I know what the error is. I'll fix it ASAP.

**Comment by sondr3** [comment]
Okay, took a bit longer than I wanted to but I've pushed a new version of `generator-jekyllized` to Github that you can install. Once you've installed it you can run `yo jekyllized:gulp [--rsync|amazon|pages]` to only update the packages and gulpfile.

**Comment by sondr3** [comment]
I meant NPM, but I'm sure you understood that, hehe. 😃

**Comment by aurerua** [comment]
It works! 
Thanks a lot the quick support on a Sunday :)

**Comment by sondr3** [comment]
No problem, let me know if you need anything else!

**Comment by DarinLevesque** [comment]
I'm still receiving the above error when running `gulp` even after updating the generator with `npm install -g generator-jekyllized`.

Is there more to it than that?

**Comment by sondr3** [comment]
Have you updated your gulpfile as well? `yo jekyllized:update` will update your gulptasks to be the latest version, just make sure to back them up if you have made any changes.

**Comment by DarinLevesque** [comment]
It was a fresh install so I didn't think an update was warranted, but am trying that now. I'll let you know in a minute. (Thanks for the quick response!)

**Comment by sondr3** [comment]
Really? In that case it's really strange, I'm running it as well and have no errors. Do let me know.

**Comment by DarinLevesque** [comment]
Interesting. Now after a `yo jekyllized:update` running `gulp` gives me this output:

```
assert.js:90
  throw new assert.AssertionError({
  ^
 AssertionError: Task never defined: site:tmp
    at getFunction (C:\Users\Darin\Google Drive\sites\JoB\node_modules\gulp\node_modules\undertaker\lib\helpers\normaliz
eArgs.js:15:5)
    at arrayMap (C:\Users\Darin\Google Drive\sites\JoB\node_modules\gulp\node_modules\undertaker\node_modules\lodash.map
\index.js:34:21)
    at map (C:\Users\Darin\Google Drive\sites\JoB\node_modules\gulp\node_modules\undertaker\node_modules\lodash.map\inde
x.js:138:10)
    at normalizeArgs (C:\Users\Darin\Google Drive\sites\JoB\node_modules\gulp\node_modules\undertaker\lib\helpers\normal
izeArgs.js:19:10)
    at Gulp.series (C:\Users\Darin\Google Drive\sites\JoB\node_modules\gulp\node_modules\undertaker\lib\series.js:13:14)

    at Object.<anonymous> (C:\Users\Darin\Google Drive\sites\JoB\gulpfile.js:13:30)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at execute (C:\Users\Darin\AppData\Roaming\npm\node_modules\gulp-cli\lib\versioned\^4.0.0-alpha.2\index.js:33:18)
    at Liftoff.handleArguments (C:\Users\Darin\AppData\Roaming\npm\node_modules\gulp-cli\index.js:150:63)
    at Liftoff.<anonymous> (C:\Users\Darin\AppData\Roaming\npm\node_modules\gulp-cli\node_modules\liftoff\index.js:193:1
6)
    at module.exports (C:\Users\Darin\AppData\Roaming\npm\node_modules\gulp-cli\node_modules\flagged-respawn\index.js:17
:3)
```

**Comment by sondr3** [comment]
Oh, you're using Windows. I've never tested this generator on it so I'm not sure whether this is a bug with my generator/gulp file or if it's a problem with one of the dependencies. It installed fine on my machine just now, you don't happen to have a Linux/OS X machine available you could test on? What version of Node are you running too?

**Comment by DarinLevesque** [comment]
Hahah I seriously need to just switch to a linux machine...

I'm running Node 4.4.5

**Comment by sondr3** [comment]
Strange, there shouldn't be any issues with Node 4.*. You don't have NVM so you can test it on Node 6?

**Comment by DarinLevesque** [comment]
I do. I'll give that a whirl after dinner and let you know what I find out.

**Comment by DarinLevesque** [comment]
Same thing on Node 6.2.0 with assert.js:90

Will plan on reimaging a spare to a linux distro, so I can stop having random issues. Appreciate the assist/help.

**Comment by sondr3** [comment]
No worries, if you continue to have problems when you switch to a Linux distro please let me know. I'm thinking `undertaker` might behave differently on Windows than it does on UNIX with how it looks up tasks, but I can't be sure.
